name: Cheks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use lts Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint

      # - name: Run Tests
      #   run: yarn test
